# Generated by Django 4.2.4 on 2023-09-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='eventModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=150)),
                ('total', models.DecimalField(decimal_places=2, max_digits=9)),
                ('description', models.CharField(max_length=250)),
                ('pic', models.ImageField(null=True, upload_to='media/')),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
